# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.listener.location:
        class: AppBundle\Listener\PathLocaleListener
        scope: request
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 49 }
        arguments: [@session, @security.context, @router]
